name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
      - name: Install tox
        run: pip install tox
      - name: Check manifest
        run: tox -e check-manifest
      - name: Lint
        run: tox -e lint
      - name: Mypy
        run: tox -e mypy
